"use strict";

// Phase C4A: pure V3 composition. No skill mechanics are represented here.
module.exports = function createClassBuildResolver({ content, calculateBaseStats, resolveEquipmentCombatBuild, buildPlayerCombatSnapshot }) {
  const KEYS = ["hp", "power", "defense", "crit_chance", "crit_damage", "accuracy", "dodge", "lifesteal", "resistance", "potency", "luck", "armor_penetration", "damage_reduction", "status_chance", "cooldown_reduction", "execute_threshold", "block"];
  const caps = { crit_chance: 60, dodge: 45, block: 50, lifesteal: 30, damage_reduction: 70, armor_penetration: 60, status_chance: 65, cooldown_reduction: 35, execute_threshold: 30 };
  const zeros = () => Object.fromEntries(KEYS.map((key) => [key, 0]));
  const apply = (...sets) => Object.freeze(Object.fromEntries(KEYS.map((key) => [key, Math.min(caps[key] ?? Infinity, Math.max(0, sets.reduce((sum, set) => sum + Number(set?.[key] || 0), 0)))])));
  const classByKey = new Map(content.PHASE4D_CLASS_CONTENT.classes.map((entry) => [entry.key, entry]));
  function resolveClassBuild({ profile, equipmentContributions = {} }) { if (!profile || typeof profile !== "object") throw new TypeError("A Realm profile is required."); const level = profile.realm_level ?? profile.level; const classKey = profile.class_key ?? profile.classKey ?? null; const specializationKey = profile.specialization_key ?? profile.specializationKey ?? null; if (!Number.isInteger(level) || level < 1 || level > 100) throw new TypeError("Realm level is invalid."); if (classKey !== null && (!classByKey.has(classKey) || level < 5)) throw new TypeError("Class selection is invalid."); const classDefinition = classKey ? classByKey.get(classKey) : null; const specialization = specializationKey === null ? null : classDefinition?.specializations.find((entry) => entry.key === specializationKey); if (specializationKey !== null && (!specialization || level < 20)) throw new TypeError("Specialization selection is invalid."); const baseStats = { ...zeros(), ...calculateBaseStats(level) }; const classContributions = { ...zeros(), ...(classDefinition?.contributions || {}) }; const specializationContributions = { ...zeros(), ...(specialization?.contributions || {}) }; return Object.freeze({ level, buildRevision: String(profile.build_revision ?? profile.buildRevision ?? 0), classKey, specializationKey, baseStats: Object.freeze(baseStats), classContributions: Object.freeze(classContributions), specializationContributions: Object.freeze(specializationContributions), equipmentContributions: Object.freeze({ ...equipmentContributions }), resolvedStats: apply(baseStats, classContributions, specializationContributions, equipmentContributions), skills: content.getUnlockedSkills({ level, classKey, specializationKey }) }); }
  function resolveEquipmentCombatBuildV3(readModel) { const profile = readModel?.profile; const legacy = resolveEquipmentCombatBuild(readModel); const equipmentContributions = legacy.enabled ? legacy.snapshot.equipmentContributions : {}; const build = resolveClassBuild({ profile, equipmentContributions }); const weapon = legacy.enabled ? legacy.snapshot.weapon : { source: "training_sword", publicItemId: null, itemKey: "training_sword", weaponFamily: "sword", minDamage: 6, maxDamage: 10, recoveryMs: 2500, rarity: null, quality: null, enhancementLevel: null, durabilityCurrent: null, durabilityMax: null }; const snapshot = Object.freeze({ buildSnapshotVersion: 3, equipmentContent: legacy.enabled ? legacy.snapshot.content : { version: null, key: null, hash: null }, classContent: { version: content.PHASE4D_CLASS_CONTENT_VERSION, key: content.PHASE4D_CLASS_CONTENT_KEY, hash: content.PHASE4D_CLASS_CONTENT_HASH }, skillContent: { version: content.SKILL_CONTENT_VERSION, key: content.SKILL_CONTENT_KEY, hash: content.SKILL_CONTENT_HASH }, sourceBuildRevision: build.buildRevision, level: build.level, classKey: build.classKey, specializationKey: build.specializationKey, baseStats: build.baseStats, classContributions: build.classContributions, specializationContributions: build.specializationContributions, equipmentContributions: build.equipmentContributions, resolvedStats: build.resolvedStats, weapon, armor: legacy.enabled ? legacy.snapshot.armor : [], skills: build.skills, future: { affixes: [], setBonuses: [], perks: [], mastery: {}, energyRules: null, guardRules: null, accessories: [] } }); const combatWeapon = { weaponKey: weapon.itemKey, weaponFamily: weapon.weaponFamily, minDamage: weapon.minDamage, maxDamage: weapon.maxDamage, recoveryMs: weapon.recoveryMs }; return Object.freeze({ enabled: true, model: legacy.model, snapshot, player: Object.freeze({ level: build.level, stats: snapshot.resolvedStats, weapon: combatWeapon, classKey: build.classKey, specializationKey: build.specializationKey, skills: snapshot.skills }) }); }
  return { resolveClassBuild, resolveEquipmentCombatBuildV3 };
};
