"use strict";
const content = require("@cella/realms-content");
const RARITIES = Object.freeze(["common", "uncommon", "rare", "epic", "legendary", "mythic", "celestial"]);
const STAT_CAPS = Object.freeze({ crit_chance: 60, dodge: 45, block: 50, lifesteal: 30, damage_reduction: 70, armor_penetration: 60, status_chance: 65, cooldown_reduction: 35, execute_threshold: 30 });
const DURABILITY_RANGES = Object.freeze({ common: [70, 100], uncommon: [100, 140], rare: [140, 190], epic: [190, 250], legendary: [250, 320], mythic: [320, 390], celestial: [400, 450] });
const QUALITY_BOUNDARIES = Object.freeze([{ quality: "poor", upperExclusive: .07 }, { quality: "standard", upperExclusive: .60 }, { quality: "fine", upperExclusive: .85 }, { quality: "pristine", upperExclusive: .97 }, { quality: "perfect", upperExclusive: 1 }]);
const WEAPON_RECOVERY_MS = Object.freeze({ dagger: 2000, sword: 2500, bow: 2750, spear: 3000, staff: 3000, tome: 3250, crossbow: 3500, scythe: 3500, hammer: 4250, greatsword: 4500 });
const COMBAT_CONFIG = Object.freeze({ schemaVersion: 1, baseHitChance: 95, minimumHitChance: 50, maximumHitChance: 99, defenseConstant: 200, maximumMitigation: 70, minimumLandedDamage: 1, maxRecentEvents: 12, supportedModes: Object.freeze(["solo_hunt"]), supportedActions: Object.freeze(["basic_attack"]), weaponRecoveryMs: WEAPON_RECOVERY_MS, statCaps: STAT_CAPS });
const HUNT_ENCOUNTER_CONFIG = Object.freeze({ minibossReplacementChance: .08 }); const INACTIVITY_MS = 5 * 60 * 1000;
const TRAINING_SWORD = Object.freeze({ weaponKey: "training_sword", displayName: "Training Sword", weaponFamily: "sword", minDamage: 6, maxDamage: 10, recoveryMs: 2500 });
function error(code, message, details) { const value = new Error(message || code); value.name = "RealmCombatError"; value.code = code; value.details = details; return value; }
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function roll(rng) { if (typeof rng !== "function") throw error("COMBAT_INVALID_ACTION", "A deterministic RNG function is required."); const value = rng(); if (!Number.isFinite(value) || value < 0 || value >= 1) throw error("INVALID_RNG_ROLL", "RNG must return 0 <= roll < 1."); return value; }
function inclusive(values, rng) { return values[0] + Math.floor(roll(rng) * (values[1] - values[0] + 1)); }
function calculateBaseStats(level) { if (!Number.isInteger(level) || level < 1 || level > 100) throw new RangeError("Realm level must be 1–100."); const d = level - 1; return Object.freeze({ hp: 100 + 12 * d, power: 10 + Math.floor(1.2 * d), defense: 8 + Math.floor(.9 * d), crit_chance: 5, crit_damage: 150, accuracy: 0, dodge: 5, lifesteal: 0, resistance: 0, potency: 0, luck: 0 }); }
function xpForNextLevel(level) { if (!Number.isInteger(level) || level < 1 || level >= 100) return 0; return 100 + 35 * level + 12 * level * level; }
function applyXp(level, xp, amount) { if (!Number.isSafeInteger(amount) || amount < 0) throw new RangeError("XP amount must be a nonnegative safe integer."); let nextLevel = level, nextXp = xp, remaining = amount; while (nextLevel < 100) { const required = xpForNextLevel(nextLevel); if (nextXp + remaining < required) { nextXp += remaining; remaining = 0; break; } remaining -= required - nextXp; nextLevel++; nextXp = 0; } if (nextLevel === 100) nextXp = 0; return { level: nextLevel, xp: nextXp, awarded: amount, discardedAtCap: remaining }; }
function validateWeapon(weapon) { if (!weapon || !Number.isInteger(weapon.minDamage) || !Number.isInteger(weapon.maxDamage) || weapon.minDamage < 0 || weapon.maxDamage < weapon.minDamage || !Number.isInteger(weapon.recoveryMs) || weapon.recoveryMs <= 0) throw error("COMBAT_INVALID_STATE", "Weapon snapshot is invalid."); return weapon; }
function cap(value, max) { return Math.min(max, Math.max(0, Number.isFinite(value) ? value : 0)); }
function hitChance(attacker, target) { return Math.min(COMBAT_CONFIG.maximumHitChance, Math.max(COMBAT_CONFIG.minimumHitChance, COMBAT_CONFIG.baseHitChance + (attacker.accuracy || 0) - cap(target.dodge, STAT_CAPS.dodge))); }
function resolveDirectDamage({ attacker, target, weapon, rng, skillMultiplier = 1 }) { validateWeapon(weapon); const chance = hitChance(attacker, target); if (roll(rng) * 100 >= chance) return { hit: false, critical: false, hitChance: chance, critChance: cap(attacker.crit_chance, STAT_CAPS.crit_chance), weaponRoll: null, rawDamage: 0, effectiveDefense: 0, mitigation: 0, finalDamage: 0, rngConsumed: 1 }; const weaponRoll = inclusive([weapon.minDamage, weapon.maxDamage], rng); const critical = roll(rng) * 100 < cap(attacker.crit_chance, STAT_CAPS.crit_chance); const rawDamage = (weaponRoll * skillMultiplier + attacker.power * .5) * (critical ? (attacker.crit_damage || 150) / 100 : 1); const effectiveDefense = Math.max(0, target.defense * (1 - cap(attacker.armor_penetration, STAT_CAPS.armor_penetration) / 100)); const mitigation = Math.min(COMBAT_CONFIG.maximumMitigation / 100, Math.max(0, effectiveDefense / (effectiveDefense + COMBAT_CONFIG.defenseConstant))); return { hit: true, critical, hitChance: chance, critChance: cap(attacker.crit_chance, STAT_CAPS.crit_chance), weaponRoll, rawDamage, effectiveDefense, mitigation, finalDamage: Math.max(1, Math.floor(rawDamage * (1 - mitigation))), rngConsumed: 3 }; }
function normalizeStats(level, supplied = {}) { const base = calculateBaseStats(level); return { ...base, armor_penetration: 0, damage_reduction: 0, status_chance: 0, cooldown_reduction: 0, execute_threshold: 0, block: 0, ...clone(supplied) }; }
function createSoloHuntState({ combatId, guildId, playerId, player, weapon, encounterKey, createdAt, buildSnapshot = null }) { const enemy = content.getVeyraEncounter(encounterKey); if (!enemy) throw error("COMBAT_UNKNOWN_ENCOUNTER", "Unknown combat encounter."); if (!player || !Number.isInteger(player.level)) throw error("COMBAT_INVALID_STATE", "Player combat snapshot is invalid."); validateWeapon(weapon); const playerStats = normalizeStats(player.level, player.stats); const enemyStats = normalizeStats(enemy.level, enemy.stats); const schemaVersion = buildSnapshot?.buildSnapshotVersion === 3 ? 3 : buildSnapshot ? 2 : 1; return { schemaVersion, version: 1, combatId, mode: "solo_hunt", status: "active", guildId, playerId, encounterKey, turnNumber: 1, player: { level: player.level, currentHp: playerStats.hp, maxHp: playerStats.hp, stats: playerStats, weapon: clone(weapon), ...(buildSnapshot ? { buildSnapshot: clone(buildSnapshot) } : {}), ...(schemaVersion === 3 ? { classKey: player.classKey, specializationKey: player.specializationKey, skills: clone(player.skills || []) } : {}), statuses: [] }, enemy: { key: enemy.key, displayName: enemy.displayName, world: enemy.world, encounterType: enemy.encounterType, level: enemy.level, currentHp: enemy.maxHp, maxHp: enemy.maxHp, stats: enemyStats, weapon: clone(enemy.weapon), statuses: [] }, nextActionAt: createdAt, createdAt, updatedAt: createdAt, result: null, recentEvents: [{ type: "combat_started", actor: "system", target: null, amount: null, critical: false, metadata: { encounterKey } }] }; }
function validateCombatState(state) { if (!state || ![1, 2, 3].includes(state.schemaVersion) || !["active", "victory", "defeat", "cancelled", "expired"].includes(state.status) || !Number.isInteger(state.version) || state.version < 1 || !Number.isInteger(state.turnNumber) || state.turnNumber < 1) throw error("COMBAT_INVALID_STATE", "Combat state is invalid."); for (const actor of [state.player, state.enemy]) { if (!actor || !Number.isFinite(actor.currentHp) || !Number.isFinite(actor.maxHp) || actor.currentHp < 0 || actor.currentHp > actor.maxHp) throw error("COMBAT_INVALID_STATE", "Combat HP snapshot is invalid."); validateWeapon(actor.weapon); } return state; }
function event(type, actor, target, fields = {}) { return { type, actor, target, amount: fields.amount == null ? null : fields.amount, critical: Boolean(fields.critical), metadata: fields.metadata || {} }; }
function attack(attacker, target, rng) { const resolution = resolveDirectDamage({ attacker: attacker.stats, target: target.stats, weapon: attacker.weapon, rng }); const events = [event("attack", null, null)]; if (!resolution.hit) { events.push(event("attack_missed", null, null, { metadata: { hitChance: resolution.hitChance } })); return { resolution, events, targetHp: target.currentHp }; } if (resolution.critical) events.push(event("critical_hit", null, null)); const targetHp = Math.max(0, target.currentHp - resolution.finalDamage); events.push(event("damage_dealt", null, null, { amount: resolution.finalDamage, critical: resolution.critical, metadata: { mitigation: resolution.mitigation } })); return { resolution, events, targetHp }; }
function resolveCombatAction({ state, action, nowMs, expectedVersion, rng }) { validateCombatState(state); if (state.status !== "active") throw error("COMBAT_NOT_ACTIVE", "Combat is not active."); if (!Number.isInteger(expectedVersion) || expectedVersion !== state.version) throw error("COMBAT_VERSION_MISMATCH", "Combat state version does not match.", { expectedVersion: state.version }); if (action?.type !== "basic_attack") throw error("COMBAT_INVALID_ACTION", "Unsupported combat action."); if (!Number.isFinite(nowMs)) throw error("COMBAT_INVALID_ACTION", "nowMs must be finite."); if (nowMs < state.nextActionAt) throw error("WEAPON_RECOVERING", "Weapon is recovering.", { nextActionAt: state.nextActionAt, remainingMs: state.nextActionAt - nowMs }); const next = clone(state); const player = attack(next.player, next.enemy, rng); const events = player.events.map((entry) => ({ ...entry, actor: entry.actor || "player", target: entry.target || "enemy" })); events[0].type = "player_attack"; next.enemy.currentHp = player.targetHp; let enemy = null; if (next.enemy.currentHp === 0) { next.status = "victory"; next.result = { outcome: "victory", winner: "player" }; events.push(event("combat_victory", "system", null)); } else { enemy = attack(next.enemy, next.player, rng); const enemyEvents = enemy.events.map((entry) => ({ ...entry, actor: entry.actor || "enemy", target: entry.target || "player" })); enemyEvents[0].type = "enemy_attack"; events.push(...enemyEvents); next.player.currentHp = enemy.targetHp; if (next.player.currentHp === 0) { next.status = "defeat"; next.result = { outcome: "defeat", winner: "enemy" }; events.push(event("combat_defeat", "system", null)); } } next.version++; next.turnNumber++; next.updatedAt = nowMs; next.nextActionAt = nowMs + next.player.weapon.recoveryMs; next.recentEvents = events.slice(-COMBAT_CONFIG.maxRecentEvents); return { state: next, events, playerAttack: player.resolution, enemyAttack: enemy?.resolution || null }; }
function selectVeyraEncounter(level, rng) { if (!Number.isInteger(level) || level < 1 || level > 100) throw new RangeError("player level must be 1–100."); const type = roll(rng) < .08 ? "miniboss" : "normal"; const entries = Object.values(content.VEYRA_ENCOUNTERS).filter((entry) => entry.encounterType === type).map((entry) => ({ entry, weight: 1 / (1 + (level - entry.level) ** 2) })); let cursor = roll(rng) * entries.reduce((total, entry) => total + entry.weight, 0); for (const entry of entries) { cursor -= entry.weight; if (cursor <= 0) return content.getVeyraEncounter(entry.entry.key); } return content.getVeyraEncounter(entries.at(-1).entry.key); }
function buildPlayerCombatSnapshot(profile) { const level = Number(profile?.realm_level ?? profile?.level); if (!Number.isInteger(level) || level < 1 || level > 100) throw new RangeError("Realm profile has no valid level."); return { level, stats: { ...calculateBaseStats(level) }, weapon: { ...TRAINING_SWORD } }; }
function rollEquipmentInstance({ definition, rarity, rng }) { if (!definition || (definition.itemType ?? definition.item_type) !== "equipment" || !RARITIES.includes(rarity)) throw error("INVALID_ITEM_DEFINITION", "An equipment definition and rarity are required."); const qualityRoll = roll(rng); const quality = QUALITY_BOUNDARIES.find((entry) => qualityRoll < entry.upperExclusive).quality; const durable = Boolean(definition.durabilityEnabled ?? definition.durability_enabled) && ["weapon", "helmet", "chest", "gloves", "legs", "boots"].includes(definition.subtype); if (!durable) return { quality, enhancementLevel: 0, durabilityCurrent: null, durabilityMax: null }; const durabilityMax = inclusive(DURABILITY_RANGES[rarity], rng); return { quality, enhancementLevel: 0, durabilityCurrent: durabilityMax, durabilityMax }; }
const HUNT_LOOT_CONFIG = Object.freeze({ normalDropUpperExclusive: .12, minibossOutcomes: Object.freeze({ armorUpperExclusive: .25, weaponUpperExclusive: .35 }), normalRarity: Object.freeze([{ rarity: "common", upperExclusive: .70 }, { rarity: "uncommon", upperExclusive: .95 }, { rarity: "rare", upperExclusive: 1 }]), minibossRarity: Object.freeze([{ rarity: "common", upperExclusive: .35 }, { rarity: "uncommon", upperExclusive: .80 }, { rarity: "rare", upperExclusive: .98 }, { rarity: "epic", upperExclusive: 1 }]) });
function createHuntReward({ encounter, rng }) { if (!encounter || !["normal", "miniboss"].includes(encounter.encounterType)) throw new TypeError("A Veyra normal or miniboss encounter is required."); const inRange = (value) => value.min + Math.floor(roll(rng) * (value.max - value.min + 1)); const xp = inRange(encounter.rewards.xp), credits = inRange(encounter.rewards.credits), scrap = scrapFor(encounter.encounterType, rng); const outcome = equipmentOutcome(encounter.encounterType, rng); let loot = null; if (outcome) { const pool = outcome === "weapon" ? content.VEYRA_WEAPON_DROPS : outcome === "armor" ? content.VEYRA_ARMOR_DROPS : content.VEYRA_HUNT_DROP_DEFINITIONS; const definition = pool[Math.floor(roll(rng) * pool.length)]; const rarity = rarityFor(encounter.encounterType, rng); const instance = rollEquipmentInstance({ definition, rarity, rng }); loot = { item_key: definition.itemKey, rarity, quality: instance.quality, enhancement_level: instance.enhancementLevel, durability_current: instance.durabilityCurrent, durability_max: instance.durabilityMax }; } return { reward_version: 2, xp, credits, scrap, encounter_key: encounter.key, encounter_type: encounter.encounterType, loot }; }
function getVictoryLevelXpMultiplier({ playerLevel, enemyLevel }) { if (!Number.isSafeInteger(playerLevel) || playerLevel < 1 || playerLevel > 100 || !Number.isSafeInteger(enemyLevel) || enemyLevel < 1 || enemyLevel > 100) throw new RangeError("Player and enemy levels must be safe integers from 1 to 100."); const levelDifference = Math.min(5, Math.max(0, enemyLevel - playerLevel)); return { levelDifference, multiplier: 1 + levelDifference * .1 }; }
function applyVictoryLevelXpBonus({ baseXp, playerLevel, enemyLevel }) { if (!Number.isSafeInteger(baseXp) || baseXp < 0) throw new RangeError("Base XP must be a nonnegative safe integer."); const { levelDifference, multiplier } = getVictoryLevelXpMultiplier({ playerLevel, enemyLevel }); const finalXp = Math.floor(baseXp * multiplier); if (!Number.isSafeInteger(finalXp)) throw new RangeError("Final XP exceeds safe integer range."); return { baseXp, bonusXp: finalXp - baseXp, finalXp, levelDifference, multiplier }; }
function createHuntDefeatXp({ encounter, rng }) { if (!encounter || !["normal", "miniboss"].includes(encounter.encounterType) || !Number.isSafeInteger(encounter.rewards?.xp?.min) || !Number.isSafeInteger(encounter.rewards?.xp?.max) || encounter.rewards.xp.min <= 0 || encounter.rewards.xp.max < encounter.rewards.xp.min) throw new TypeError("A Veyra normal or miniboss encounter with a valid XP range is required."); const rolledXp = inclusive([encounter.rewards.xp.min, encounter.rewards.xp.max], rng); return Math.max(1, Math.floor(rolledXp * .25)); }
function deriveDurabilityWearIntent({ action, result }) { if (action?.type !== "basic_attack" || !result?.state) throw new TypeError("An accepted Basic Attack result is required."); return Object.freeze({ weapon: 1, armor: result.enemyAttack?.hit === true }); }
function selectWeightedEncounter(level, candidates, value) { const weighted = candidates.map((entry) => ({ entry, weight: 1 / (1 + (level - entry.level) ** 2) })); let cursor = value * weighted.reduce((total, entry) => total + entry.weight, 0); for (const entry of weighted) { cursor -= entry.weight; if (cursor <= 0) return content.getVeyraEncounter(entry.entry.key); } return content.getVeyraEncounter(weighted.at(-1).entry.key); }
function equipmentOutcome(encounterType, rng) { const value = roll(rng); return encounterType === "normal" ? (value < HUNT_LOOT_CONFIG.normalDropUpperExclusive ? "any" : null) : value < HUNT_LOOT_CONFIG.minibossOutcomes.armorUpperExclusive ? "armor" : value < HUNT_LOOT_CONFIG.minibossOutcomes.weaponUpperExclusive ? "weapon" : null; }
function rarityFor(encounterType, rng) { const table = encounterType === "miniboss" ? HUNT_LOOT_CONFIG.minibossRarity : HUNT_LOOT_CONFIG.normalRarity; const rarityRoll = roll(rng); return table.find((entry) => rarityRoll < entry.upperExclusive).rarity; }
function scrapFor(encounterType, rng) { if (encounterType === "miniboss") return inclusive([8, 18], rng); const scrapRoll = roll(rng); return [2, 3, 4, 5, 6, 7].find((_, index) => scrapRoll < [.18, .39, .61, .79, .92, 1][index]); }
const combatBuild = require("./combat-build")({ calculateBaseStats, trainingSword: TRAINING_SWORD });
const classBuild = require("./class-build")({ content, calculateBaseStats, resolveEquipmentCombatBuild: combatBuild.resolveEquipmentCombatBuild, buildPlayerCombatSnapshot });
module.exports = { RARITIES, STAT_CAPS, DURABILITY_RANGES, QUALITY_BOUNDARIES, WEAPON_RECOVERY_MS, COMBAT_CONFIG, HUNT_ENCOUNTER_CONFIG, INACTIVITY_MS, TRAINING_SWORD, error, clone, roll, inclusive, calculateBaseStats, xpForNextLevel, applyXp, validateWeapon, hitChance, calculateHitChance: hitChance, resolveDirectDamage, createSoloHuntState, validateCombatState, resolveCombatAction, selectWeightedEncounter, selectVeyraEncounter, buildPlayerCombatSnapshot, rollEquipmentInstance, HUNT_LOOT_CONFIG, equipmentOutcome, rarityFor, scrapFor, createHuntReward, getVictoryLevelXpMultiplier, applyVictoryLevelXpBonus, createHuntDefeatXp, deriveDurabilityWearIntent, ...combatBuild, ...classBuild };
